### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by shadowdevnotreal** [blackhatethicalhacking/SQLMutant#2]
When this runs arjun
I get this a lot

[-] Target is misbehaving. Try the --stable switch.
[!] No parameters were discovered.

Maybe add feature to recheck the fails?
I love working with you all but I am newbie.....would not know where to begin.

**Comment by blackhatethicalhacking** [comment]
If you add the --stable switch, it will take much more time to do the scans, with that, it still is ok, because it is having lots of requests, another tip is you can always ctrl +c during arjun, after a while and it will resume the process with whatever it fetched to the point you cancelled arjun, so it can start.

**Comment by shadowdevnotreal** [comment]
Suhweet!
Did not know this.
I used this tool and it found me 5 open bugs.
Now..... if only I knew what to do with this information. Lol.
Scan ran for 48 hours. Good God.
What's the traffic like coming from this?
Passive?

**Comment by Xitro01** [comment]
> When this runs arjun I get this a lot
> 
> [-] Target is misbehaving. Try the --stable switch. [!] No parameters were discovered.
> 
> Maybe add feature to recheck the fails? I love working with you all but I am newbie.....would not know where to begin.

This is a known issue with Arjun, should be solved with version 2.2.7. I don't get this issue, I have some other issues that will probably be solved in newer versions.

To answer your other question: No this is not passive at all, this is really intrusive scanning.

If you don't know what to do with that information, hit me up (chrisz89 on Discord), we could collaborate.

@blackhatethicalhacking Thanks for sharing this, love to see the view of others. Probably not going to use this as is, but definately gave me some ideas. The script only focusses on MySQL databases and also use all tamper scripts even the ones that are only used for ASP.NET servers, which probably use MSSQL and not MySQL. So there are a lot of things that could be finetuned.

**Comment by blackhatethicalhacking** [comment]
> When this runs arjun
> 
> I get this a lot
> 
> 
> 
> [-] Target is misbehaving. Try the --stable switch.
> 
> [!] No parameters were discovered.
> 
> 
> 
> Maybe add feature to recheck the fails?
> 
> I love working with you all but I am newbie.....would not know where to begin.

Hey yeah that has to do with the website and protection mechanisms behind it so depends on the target u can add the stable by editing our script but would take longer nevertheless it will still work but passively if it finds stuff we addressed this well hope this helps as its related to arjun but also the target
