### ISSUE TITLE
cannot install fortune-mod on mac m1 ventura

### ISSUE THREAD

**Issue by AzhariRamadhan** [blackhatethicalhacking/SQLMutant#3]
We have some housekeeping to take care of first!
fortune-mod not found, installing...
Error: package manager not found, please install fortune-mod manually

**Comment by blackhatethicalhacking** [comment]
:) try this: sudo apt-get install -y fortune

Not sure which Linux you are using, but essentially, you want to install the Fortune package

**Comment by AzhariRamadhan** [comment]
brew install fortune
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
Warning: fortune 9708 is already installed and up-to-date.
To reinstall 9708, run:
  brew reinstall fortune

**Comment by AzhariRamadhan** [comment]
<img width="762" alt="Jepretan Layar 2023-03-07 pukul 19 37 28" src="https://user-images.githubusercontent.com/32870854/223424224-5c3d554f-f6f8-4a80-bda7-feac51479a0b.png">

**Comment by blackhatethicalhacking** [comment]
I just modified it and removed the fortune-mod check, can you type:

`git pull & git stash`

And let me know if you have the latest version installed, it should update something, so I removed the fortune-mod part from it.

And try again :)

**Comment by AzhariRamadhan** [comment]
it work, thanks


<img width="762" alt="Jepretan Layar 2023-03-07 pukul 20 07 30" src="https://user-images.githubusercontent.com/32870854/223430972-0fac2294-8f72-486a-9c76-6138164d7f4e.png">
